load_file_format: "csv"
drop_columns: ["first_name", "last_name", "cc_n"]
join_on_column: "id"
join_method: "inner"
filter_on_column: "country"
rename_columns: {"id": "client_identifier",
                "btc_a": "bitcoin_address",
                "cc_t": "credit_card_type"}
save_file_format: "csv"
saving_mode: "overwrite"